### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by macebal1** [nicc00/project#3]
- The logo does not visually look centered in the hope page 
- Add a navigation bar that pops with the scroll or add a "back to top" button to make it easier for user 
- Content (ratings and movie info) are not visually the same across the different pages 
- You could make the contact form more professional, not just a feedback box

Overall, very interesting!!

**Comment by nicc00** [comment]
Thanks for the feedback! I think a fixed nav bar is a great idea so I just added it.
