### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by rwinn1** [nicc00/project#4]
Technical
1. Add links to the reviews (Rotten Tomatoes, IMBD) so users can view the full reviews

Content:
1. Add your own short review about the movie
2. Center the "the movie place", it just looks slightly off from "contact" below it

I really like City of God, but have not seen the other movies so ill have to check them out. Nice work!

**Comment by nicc00** [comment]
Thanks for the suggestions, I will definitely add links to the review sites. Also, my header was a bit messed up, "contact" should have been on the right of the page not below the title.
